name: Workflow
on:
  push: 
    branches:
        - feat

jobs:
  SAST:
    runs-on: ubuntu-24.04
    steps: 
      - uses: actions/checkout@v3
        with: 
            fetch-depth: 0
      - name: SonarCloud Scan
        uses: Sonarsource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}  
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
        with:
          args: >
              -Dsonar.organization="laboratorio-nunez-reyes"
              -Dsonar.projectKey="Laboratorio-Nunez-Reyes_Laboratorio-Devsecops"   


 
  SCA:
    needs: SAST
    runs-on: ubuntu-24.04
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      env:
        JAVA_HOME: /opt/jdk
      id: Depcheck
      with:
        project: '${{ github.event.repository.name }}'
        path: '.'
        format: 'HTML'
        args: >
          --out ./reports
          --failOnCVSS 0
          --enableRetired

    - name: Upload Test Result
      uses: actions/upload-artifact@master
      with:
        name: Depcheck Report
        path: ./reports


  DockerBuild:
    needs: SCA
    runs-on: ubuntu-24.04
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Build
      run: |
        docker build --tag emanuelnunezf/laboratorio-n-r:latest .

    - name: Push Docker
      run: |
        docker push emanuelnunezf/laboratorio-n-r:latest

  DockerScan:
    needs: DockerBuild
    runs-on: ubuntu-24.04
    steps:
    
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Pull Docker
      run: |
        docker pull emanuelnunezf/laboratorio-n-r:latest

    - name: Run Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'emanuelnunezf/laboratorio-n-r:latest'
        format: 'table'